[package]
authors = ["David Flemstr√∂m <david.flemstrom@gmail.com>"]
description = "High-level bindings to V8, the Javascript engine"
keywords = ["v8", "javascript", "js", "ecmascript", "google"]
name = "v8"
license = "Apache-2.0"
repository = "https://github.com/dflemstr/v8-rs"
version = "0.3.0"

[dependencies]
error-chain = "0.5.0"
lazy_static = "0.2.1"
v8-ng-sys = "0.2.1"

[features]
shared = ["v8-ng-sys/shared"]
