[package]
authors = ["David FlemstrÃ¶m <david.flemstrom@gmail.com>"]
name = "v8"
version = "0.1.0"

[dependencies]
error-chain = "0.5.0"
lazy_static = "0.2.1"

[dependencies.v8-ng-sys]
path = "v8-sys"

[features]
shared = ["v8-ng-sys/shared"]
