[package]
authors = ["David Flemstr√∂m <david.flemstrom@gmail.com>"]
build = "build.rs"
description = "Low-level bindings to V8, the Javascript engine"
documentation = "https://dflemstr.github.io/v8-rs/v8_sys/index.html"
homepage = "https://dflemstr.github.io/v8-rs"
include = ["build.rs", "src/**/*", "Cargo.toml"]
keywords = ["v8", "javascript", "js", "ecmascript", "google"]
name = "v8-sys"
license = "Apache-2.0"
repository = "https://github.com/dflemstr/v8-rs/tree/master/v8-sys"
version = "0.11.0"

[build-dependencies]
bindgen = "0.19.0"
clang = "0.12.0"
gcc = "0.3.35"
v8-api = { version = "0.4.0", path = "../v8-api" }

[dev-dependencies]
lazy_static = "0.2.1"

[features]
shared = []
